import type { DataCollection } from '@wix/astro/builders'

export const collectionIdSuffix = 'listings';

export default {
  idSuffix: collectionIdSuffix,
  displayName: 'Marketplace Listings',
  fields: [
    { type: 'TEXT', key: 'sellerId' },
    { type: 'TEXT', key: 'sellerName' },
    { type: 'TEXT', displayName: 'Title', key: 'title' },
    { type: 'RICH_TEXT', key: 'description' },
    { type: 'NUMBER', key: 'price' },
    { type: 'TEXT', key: 'currency' },
    { type: 'TEXT', key: 'categoryId' },
    { type: 'TEXT', key: 'subcategoryId' },
    { type: 'TEXT', key: 'condition' },
    { type: 'TEXT', key: 'location' },
    { type: 'TEXT', key: 'city' },
    { type: 'TEXT', key: 'country' },
    { type: 'IMAGE', key: 'image' },
    { type: 'MEDIA_GALLERY', key: 'images' },
    { type: 'IMAGE', key: 'coverImage' },
    { type: 'TEXT', key: 'status' },
    { type: 'NUMBER', key: 'views' },
    { type: 'NUMBER', key: 'favoriteCount' },
    { type: 'NUMBER', key: 'messageCount' },
    { type: 'DATETIME', key: 'publishedAt' },
    { type: 'DATETIME', key: 'createdAt' },
    { type: 'DATETIME', key: 'updatedAt' },
  ],
  displayField: 'title',
  dataPermissions: {
    itemInsert: 'PRIVILEGED',
    itemRead: 'ANYONE',
    itemRemove: 'PRIVILEGED',
    itemUpdate: 'PRIVILEGED',
  },
  indexes: [],
  initialData: [
    {
      title: 'Mid-century lounge chair',
      description: 'A comfortable walnut-frame lounge chair with warm woven upholstery, ready for a new home.',
      price: 240,
      currency: 'USD',
      categoryId: 'furniture',
      condition: 'GOOD',
      location: 'Ikeja, Lagos',
      city: 'Ikeja',
      country: 'Nigeria',
      sellerId: 'seed-seller-1',
      sellerName: 'Lagos Home Finds',
      image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 128, favoriteCount: 18, messageCount: 4,
    },
    {
      title: 'Classic red leather sneakers',
      description: 'Clean, lightly worn leather sneakers with plenty of life left in them.',
      price: 85,
      currency: 'USD',
      categoryId: 'fashion',
      condition: 'LIKE_NEW',
      location: 'Yaba, Lagos',
      city: 'Yaba',
      country: 'Nigeria',
      sellerId: 'seed-seller-2',
      sellerName: 'The Style Rack',
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 204, favoriteCount: 31, messageCount: 7,
    },
    {
      title: 'Minimal steel wristwatch',
      description: 'Simple silver-tone wristwatch with a clean black dial and fresh battery.',
      price: 120,
      currency: 'USD',
      categoryId: 'accessories',
      condition: 'GOOD',
      location: 'Victoria Island, Lagos',
      city: 'Victoria Island',
      country: 'Nigeria',
      sellerId: 'seed-seller-3',
      sellerName: 'Everyday Objects',
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 96, favoriteCount: 12, messageCount: 2,
    },
    {
      title: 'Small-batch coffee beans',
      description: 'Freshly roasted whole beans with chocolate and citrus notes. 250g bag.',
      price: 18,
      currency: 'USD',
      categoryId: 'food-drink',
      condition: 'NEW',
      location: 'Lekki Phase 1, Lagos',
      city: 'Lekki',
      country: 'Nigeria',
      sellerId: 'seed-seller-4',
      sellerName: 'Harbor Coffee',
      image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 173, favoriteCount: 24, messageCount: 5,
    },
    {
      title: 'Portable work laptop',
      description: 'Slim laptop suitable for work, study, and everyday browsing. Charger included.',
      price: 560,
      currency: 'USD',
      categoryId: 'electronics',
      condition: 'GOOD',
      location: 'Surulere, Lagos',
      city: 'Surulere',
      country: 'Nigeria',
      sellerId: 'seed-seller-5',
      sellerName: 'Tech Exchange',
      image: 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 287, favoriteCount: 39, messageCount: 11,
    },
    {
      title: 'Everyday acetate sunglasses',
      description: 'Polarized sunglasses with a classic frame and protective case.',
      price: 45,
      currency: 'USD',
      categoryId: 'accessories',
      condition: 'NEW',
      location: 'Gwarinpa, Abuja',
      city: 'Gwarinpa',
      country: 'Nigeria',
      sellerId: 'seed-seller-6',
      sellerName: 'Sunroom Supply',
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1200&q=85',
      coverImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1200&q=85',
      images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=1200&q=85'],
      status: 'ACTIVE', views: 142, favoriteCount: 16, messageCount: 3,
    },
  ],
} satisfies DataCollection;
